name: 'Update Slack Info'
description: 'This action will update Slack Information like groups or users'
author: 'pipo02mix'
runs:
  using: 'docker'
  image: 'docker://quay.io/giantswarm/update-slack-info:v1.0.0'
branding:
  icon: 'bell'
  color: 'yellow'
